<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>PHP</title>
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="css/movies.css">
</head>
<body>
    <h1>Les films du moment</h1>

        <ul class="movie-list">
            <?php foreach($movies as $movie): ?>
                <li>
                    <img src="images/<?= $covers[$movie['cover']] ?>">
                    <p>
                        <strong><?= $movie['title'] ?></strong> -
                        <em><?= convertDuration($movie['duration']) ?></em>
                    </p>
                </li>
            <?php endforeach; ?>
        </ul>

    <form action="research_duration.php" method="post">
      <h2>Recherche par durée maximum d'un film</h2>
      <p>
        <label for="search">Durée du film : </label>
        <input id="search" type="search" name="research_duration" value="" /> min
        <input type="submit" name="submit" value="Rechercher" />
      </p>
    </form>

    <form action="research-cinema.php" method="post">
      <h2>Recherche par un cinéma</h2>
      <select name="cinema">
        <option value=""> - Choisir le cinéma - </option>
        <?php foreach($cinema as $key => $value):?>
            <option value="<?= $key ?>"><?= $value ?></option>
        <?php endforeach;?>
      </select>
      <input type="submit" name="submit" value="Rechercher" />
    </form>

</body>
</html>
